version: '3.8'

services:
  mcp-logging-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-logging-server
    restart: unless-stopped
    ports:
      - "9080:9080"  # Log ingestion API
      - "8081:8081"  # MCP server
    environment:
      - MCP_LOGGING_DB_CONNECTION=/app/data/logs.db
      - MCP_LOGGING_CONFIG_PATH=/app/config/config.yaml
      - MCP_LOGGING_RECOVERY_DIR=/app/recovery
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./recovery:/app/recovery
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-logging-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

  # Reverse proxy for production deployment
  traefik:
    image: traefik:v2.10
    container_name: mcp-logging-traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@example.com}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
      - "8090:9080"  # Traefik dashboard (only for development)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/letsencrypt:/letsencrypt
    networks:
      - mcp-logging-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
    environment:
      - TRAEFIK_API_DASHBOARD=true

networks:
  mcp-logging-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  traefik_letsencrypt:
    driver: local