server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # MCP Logging Server application logs
  - job_name: mcp-logging-server
    static_configs:
      - targets:
          - localhost
        labels:
          job: mcp-logging-server
          __path__: /var/log/mcp/*.log
    pipeline_stages:
      - match:
          selector: '{job="mcp-logging-server"}'
          stages:
            - json:
                expressions:
                  level: level
                  message: message
                  service_name: service_name
                  timestamp: timestamp
            - labels:
                level:
                service_name:
            - timestamp:
                source: timestamp
                format: RFC3339

  # Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/log/docker/containers/*/*-json.log
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{job="docker"}'
          stages:
            - json:
                expressions:
                  log: log
                  stream: stream
                  time: time
            - json:
                expressions:
                  message: log
                source: log
            - timestamp:
                source: time
                format: RFC3339
            - output:
                source: message

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/system.log
    pipeline_stages:
      - match:
          selector: '{job="system"}'
          stages:
            - regex:
                expression: '(?P<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\w+)\s+(?P<process>\w+)\[(?P<pid>\d+)\]:\s+(?P<message>.*)'
            - timestamp:
                source: timestamp
                format: 'Jan 2 15:04:05'
            - labels:
                hostname:
                process:
                pid: